version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
      - //host.docker.internal/z/Homeflix:/mnt/nas/Homeflix
    environment:
      - TMDB_API_KEY=${TMDB_API_KEY}